[workspace]
resolver = "2"
members = [
    "ansi",
    "ansiart",
    "ansiplay",
    "ansiterm",
    "basic_waves",
    "codepage437",
    "ega_palette",
    "img2bin",
    "sauce",
    "stdin_receiver",
]
