[package]
name = "ansiparser"
version = "0.1.0"
edition = "2021"

[dependencies]
ansiplay = { version = "^0.1", path = "../ansiplay" }
codepage437 = { version = "^0.1", path = "../codepage437" }
sauce = { version = "0.1", path = "../sauce" }
