[package]
name = "ansiart"
version = "0.1.0"
edition = "2021"

[dependencies]
ansiplay = { version = "0.1", path = "../ansiplay" }
codepage437 = { version = "0.1", path = "../codepage437" }
ega_palette = { version = "0.1", path = "../ega_palette" }
sauce = { version = "0.1", path = "../sauce" }
